export const GET_ALL = "TOURNAMENT_GET_ALL";
export const SET_ACTIVE = "TOURNAMENT_SET_ACTIVE";
export const NEW = "TOURNAMENT_CREATE_NEW";
export const NEW_ROUND = "TOURNAMENT_ROUND_CREATE_NEW";
export const UPDATE_ELO = "TOURNAMENT_ELO_UPDATE_ALL";
